import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import AuthLayout from '../../components/Auth/AuthLayout';
import AuthMessage from '../../components/Auth/AuthMessage';

function ForgotPassword() {
  return (
    <AuthLayout title="Password recovery unavailable" description="Self-service recovery needs a configured email delivery service." step="03 / 05">
      <AuthMessage type="info">Contact your StockSense administrator to reset your account password. No recovery code will be shown or generated by this application.</AuthMessage>
      <p className="auth-switch"><Link to="/login"><ArrowLeft size={14} /> Back to sign in</Link></p>
    </AuthLayout>
  );
}

export default ForgotPassword;